[workspace]
resolver = "2"
package.version = "0.1.0"
package.edition = "2021"

members = [
  "crates/ndc-sqlserver",
  "crates/query-engine/execution",
  "crates/query-engine/metadata",
  "crates/query-engine/sql",
  "crates/query-engine/translation",
]
