version: "3.6"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    platform: linux/amd64
    ports:
      - 64003:1433
    command: bash -c "/docker/entrypoint.sh"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "Password!"
      SA_PASSWORD: "Password!"
    volumes:
      - /var/opt/mssql
      - type: bind
        read_only: true
        source: ./static
        target: /static
      - type: bind
        read_only: true
        source: ./docker
        target: /docker
    healthcheck:
      test:
        - CMD-SHELL
        - |
          /opt/mssql-tools/bin/sqlcmd -U SA -P "$$SA_PASSWORD"
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 20

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./metrics/prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: volume
        source: prom_data
        target: /prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3001:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - type: bind
        source: ./metrics/grafana
        target: /etc/grafana/provisioning/datasources
        read_only: true
      - type: bind
        source: ./metrics/grafana/dashboard.yaml
        target: /etc/grafana/provisioning/dashboards/main.yaml
      - type: bind
        source: ./metrics/grafana/dashboards
        target: /var/lib/grafana/dashboards
      - type: volume
        source: grafana_data
        target: /var/lib/grafana

  auth-hook:
    build: ../v3-engine/hasura-authn-webhook/dev-auth-webhook
    init: true
    ports:
      - 3050:3050

  jaeger:
    image: jaegertracing/all-in-one:1.37
    restart: always
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 4002:16686
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 4317:4317 # OTLP gRPC
      - 4318:4318 # OTLP HTTP
      - 9411:9411
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      COLLECTOR_ZIPKIN_HOST_PORT: "9411"

volumes:
  prom_data:
  grafana_data:
