[package]
name = "ndc-sqlserver"
version.workspace = true
edition.workspace = true

default-run = "ndc-sqlserver"

[lib]
name = "ndc_sqlserver"
path = "src/lib.rs"

[[bin]]
name = "ndc-sqlserver"
path = "bin/main.rs"

[dependencies]
ndc-sdk = { git = "https://github.com/hasura/ndc-hub.git", rev = "098b1c2", package = "ndc-sdk" }
query-engine = { path = "../query-engine" }

tiberius = { version = "0.12.2", default-features = false, features = ["rustls"] }
bb8 = "0.8.1"
bb8-tiberius = "0.15.0"
async-trait = "0.1.74"
schemars = { version = "0.8.15", features = ["smol_str"] }
serde = "1.0.188"
serde_derive = "^1.0"
serde_json = { version = "1.0.108", features = ["raw_value"] }
tokio = { version = "1.33.0", features = ["full"] }
tracing = "0.1.37"
prometheus = "0.13.3"
thiserror = "1.0"

[dev-dependencies]
axum = "0.6.19"
axum-test-helper = "0.3.0"
insta = { version = "1.34.0", features = ["json"] }
env_logger = "0.10.0"
similar-asserts = "1.5.0"
