[package]
name = "query-engine-sql"

version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]

ndc-sdk = { workspace = true }

indexmap  = "2.1"

serde_json = "1.0.116"
thiserror = "1.0"
