[package]
name = "query-engine-sql"

version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]

ndc-sdk = { workspace = true }

indexmap  = "2.1"

serde_json = "1.0.116"
thiserror = "1.0"
